language: node_js

sudo: false

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

node_js:
  - '6'

script:
  - yarn test

notifications:
  email: false
