version: 2.1

orbs:
  node: circleci/node@5.0.2

parameters:
  node_version:
    type: string
    default: '16.15.1'

commands:
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1-all
          cache-key: yarn.lock
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    steps:
      - checkout
      - install_deps
      - run: yarn test
      - run: yarn test:es
      - run: yarn type-check
      - run: yarn lint:ci
